chef_mate/urls.py
from django.contrib import admin
from django.urls import path, include
from dishes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('dishes/', include('dishes.urls', namespace='dishes')),
    path("accounts/", include("django.contrib.auth.urls")),
]

dishes/urls.py
from django.urls import path
from dishes import views

app_name = 'dishes'

urlpatterns = [
    path(
        "",
        views.index,
        name="index"),
    path(
        "dish-types/",
        views.DishTypeListView.as_view(),
        name="dish-type-list"),
    path(
        "dish-types/<int:pk>/",
        views.DishTypeDetailView.as_view(),
        name="dish-type-detail"),
    path(
        "dish-types/create/",
        views.DishTypeCreateView.as_view(),
        name="dish-type-create"),
    path(
        "dish-types/<int:pk>/update/",
        views.DishTypeUpdateView.as_view(),
        name="dish-type-update"),
    path(
        "dish-types/<int:pk>/delete/",
        views.DishTypeDeleteView.as_view(),
        name="dish-type-delete"),
    path(
        "dishes/",
        views.DishListView.as_view(),
        name="dish-list"),
    path(
        "dishes/<int:pk>/",
        views.DishDetailView.as_view(),
        name="dish-detail"),
    path(
        "dishes/create/",
        views.DishCreateView.as_view(),
        name="dish-create"),
    path(
        "dishes/<int:pk>/update/",
        views.DishUpdateView.as_view(),
        name="dish-update"),
    path(
        "dishes/<int:pk>/delete/",
        views.DishDeleteView.as_view(),
        name="dish-delete"),
    path(
        "cooks/",
        views.CookListView.as_view(),
        name="cook-list"),
    path(
        "cooks/<int:pk>/",
        views.CookDetailView.as_view(),
        name="cook-detail"),
    path(
        "cooks/create/",
        views.CookCreateView.as_view(),
        name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        views.CookUpdateView.as_view(),
        name="cook-update"),
    path(
        "cooks/<int:pk>/delete/",
        views.CookDeleteView.as_view(),
        name="cook-delete"),
    path(
        'about/',
        views.about,
        name='about'),
    path(
        'contact/',
        views.contact,
        name='contact'),
]

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
    <hr class="horizontal dark mb-5">
    <div class="container text-center">
        <h6 class="text-gradient text-primary font-weight-bolder">Chef Mate</h6>
        <p class="my-4 text-sm">
            &copy; 2025 Chef Mate. All rights reserved.
        </p>
    </div>
</footer>

templates/includes/navigation-auth.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand font-weight-bold" href="/">Chef Mate</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarAuth" aria-controls="navbarAuth" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarAuth">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/navigation-light.html
<nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
  <div class="container">
    <a class="navbar-brand" href="/">Chef Mate</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarLight" aria-controls="navbarLight" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarLight">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/navigation-transparent.html
<nav class="navbar navbar-expand-lg navbar-transparent position-absolute w-100">
  <div class="container">
    <a class="navbar-brand text-white" href="/">Soft UI Design System</a>
    <button class="navbar-toggler shadow-none" type="button" data-bs-toggle="collapse" data-bs-target="#navigation">
      <span class="navbar-toggler-icon">
        <span class="navbar-toggler-bar"></span>
        <span class="navbar-toggler-bar"></span>
        <span class="navbar-toggler-bar"></span>
      </span>
    </button>
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="navbar-nav w-100">
        <!-- Pages Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Pages</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/page-about-us.html">About Us</a></li>
            <li><a class="dropdown-item" href="/page-contact-us.html">Contact Us</a></li>
            <li><a class="dropdown-item" href="/page-author.html">Author</a></li>
            <li><a class="dropdown-item" href="/page-sign-in.html">Sign In</a></li>
            <li><a class="dropdown-item" href="/page-sign-up.html">Register</a></li>
          </ul>
        </li>
        <!-- Blocks Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Blocks</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/page-sections-hero-sections.html">Page Headers</a></li>
            <li><a class="dropdown-item" href="/page-sections-features.html">Features</a></li>
            <li><a class="dropdown-item" href="/elements-buttons.html">Buttons</a></li>
          </ul>
        </li>
        <!-- Help Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Help</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="https://appseed.us/support">Support</a></li>
            <li><a class="dropdown-item" href="https://bit.ly/2NiYjQA">Getting Started</a></li>
          </ul>
        </li>
        <!-- Logout Button -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">
            <i class="fa fa-sign-out"></i> Logout
          </a>
        </li>
        <!-- Pro Version Button -->
        <li class="nav-item">
          <a href="https://appseed.us/product/soft-ui-design-pro/django/" target="_blank" class="btn btn-sm btn-white btn-round">PRO Version</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/navigation.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand font-weight-bold" href="{% url 'dishes:index' %}">Chef Mate</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'dishes:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dishes:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dishes:contact' %}">Contact</a>
        </li>
        <li class="nav-item">
          <form method="POST" action="{% url 'logout' %}" style="margin: 0; padding: 0; display: inline;">
            {% csrf_token %}
            <button type="submit" class="nav-link" style="background: none; border: none; padding: 0; line-height: 3; margin-top: -2.5px;">
              Logout
            </button>
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: {{ user.get_username }}</li>
    <li class="list-group-item">
      <a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
    </li>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}?next={{ request.path }}">Login</a>
    </li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'dishes:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'dishes:dish-type-list' %}">Dish Types</a></li>
  <li class="list-group-item"><a href="{% url 'dishes:dish-list' %}">Dishes</a></li>
  <li class="list-group-item"><a href="{% url 'dishes:cook-list' %}">Cooks</a></li>
</ul>